/* Generated by Yosys 0.43 (git sha1 ead4718e5, g++ 14.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -Os) */

(* top =  1  *)
(* src = "comp.v:1.1-23.10" *)
module comp(a, b, isbig, iseq, issmall);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* src = "comp.v:2.17-2.18" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "comp.v:2.32-2.33" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "comp.v:3.12-3.17" *)
  output isbig;
  wire isbig;
  (* src = "comp.v:3.19-3.23" *)
  output iseq;
  wire iseq;
  (* src = "comp.v:3.25-3.32" *)
  output issmall;
  wire issmall;
  assign _00_ = b[3] | ~(a[3]);
  assign _01_ = b[2] | ~(a[2]);
  assign _02_ = ~(a[3] ^ b[3]);
  assign _03_ = _02_ & ~(_01_);
  assign _04_ = _00_ & ~(_03_);
  assign _05_ = b[1] | ~(a[1]);
  assign _06_ = _02_ & ~(_05_);
  assign _07_ = a[2] ^ b[2];
  assign _08_ = _06_ & ~(_07_);
  assign _09_ = _04_ & ~(_08_);
  assign _10_ = b[0] | ~(a[0]);
  assign _11_ = _02_ & ~(_10_);
  assign _12_ = _11_ & ~(_07_);
  assign _13_ = a[1] ^ b[1];
  assign _14_ = _12_ & ~(_13_);
  assign isbig = _14_ | ~(_09_);
  assign _15_ = a[0] ^ b[0];
  assign _16_ = _15_ | _13_;
  assign _17_ = _16_ | _07_;
  assign iseq = _02_ & ~(_17_);
  assign issmall = ~(iseq | isbig);
endmodule
